// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://najnexkrzcnmgylcfjcg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ham5leGtyemNubWd5bGNmamNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMjY3OTIsImV4cCI6MjA2ODcwMjc5Mn0.8hQ0PPkzlItceSktcMKK7EukKi58e_1j5jAq-YlLiQw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});